"""'gravatar'

Revision ID: ea595efb96c0
Revises: a6bdd439ec5a
Create Date: 2017-11-19 23:45:57.185153

"""

# revision identifiers, used by Alembic.
revision = 'ea595efb96c0'
down_revision = 'a6bdd439ec5a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
